from api.tags import *


db = [
    {
        "code": "MAD",
        "description": "Madrid is a charming city. It is famous for both beautiful architecture and excellent museums. Their offer includes works by Pablo Picasso and Salvador Dalí. The Spanish capital loves fiesta, and every day the bars and clubs are full of music.",
        "pf": "1,2",
        "name": "Madrid",
        "country": "Spain",
        "lat": "40.471926",
        "long": "-3.56264",
        "tags": {EXPERIENCE, CULTURE, NIGHT_LIFE, FOOD, HOTEL, ARCHITECTURE},
        "temp": [
            9.8,
            12.0,
            16.3,
            18.2,
            22.2,
            28.2,
            32.1,
            31.3,
            26.4,
            19.4,
            13.5,
            10.0,
            20.0,
        ],
    },
    {
        "code": "ZAD",
        "description": "",
        "pf": "1,4",
        "name": "Zadar",
        "country": "Croatia",
        "lat": "44.108299",
        "long": "15.3467",
        "tags": {EXPERIENCE, CULTURE, SPORT, HOT, FOOD, ARCHITECTURE},
        "temp": [
            10.2,
            11.0,
            13.7,
            17.4,
            22.5,
            26.7,
            29.8,
            29.5,
            25.1,
            20.0,
            14.9,
            11.5,
            19.4,
        ],
    },
    {
        "code": "GVA",
        "description": "Geneva, as well as the whole Switzerland, is associated with chocolate and watches, but these are not the only products worth buying there. In Geneva, it is worth going for fashion shopping. Although the city center is full of boutiques of the best world brands, the flea market Plaine de Plainpalais, where you can find fashion retro things, is also interesting.",
        "pf": "1,6",
        "name": "Geneva",
        "country": "Switzerland",
        "lat": "46.23809814453125",
        "long": "6.108950138092041",
        "tags": {CULTURE, CITY, HOTEL, LAKE, LANDSCAPE, COLD, SPORT, SKI},
        "temp": [
            3.7,
            5.9,
            9.8,
            13.9,
            18.4,
            22.2,
            25.3,
            24.4,
            20.8,
            14.9,
            8.4,
            4.5,
            14.4,
        ],
    },
    {
        "code": "ARN",
        "description": "Stockholm, known as the Venice of the North, would have no trouble winning rivalry for the European capital city to be the most originally located – the old town is located on an island occupying a strip of land between the Baltic Sea and the great Mälaren Lake. The vicinities of Stockholm are a mosaic of pine forests, lakes and rocks.",
        "pf": "1,6",
        "name": "Stockholm",
        "country": "Sweden",
        "lat": "59.651901245116996",
        "long": "17.918600082397",
        "tags": {CITY, LANDSCAPE, SEA, HOTEL, COLD},
        "temp": [
            -1.0,
            -1.0,
            3.0,
            9.0,
            16.0,
            21.0,
            22.0,
            20.0,
            15.0,
            10.0,
            5.0,
            1.0,
            10.0,
        ],
    },
    {
        "code": "SOF",
        "description": "Sofia, the capital of Bulgaria and the largest city in the country, is one of the oldest cities of Europe. Since antiquity, the place has been influenced by both eastern and western traditions; and, as a result, Sofia is an extremely diverse city with rich tradition and culture. You can see the miraculous stone Orthodox churches, huge socialist-realist buildings, vibrant streets, and dark housing estates on the outskirts.",
        "pf": "0,9",
        "name": "Sofia",
        "country": "Bulgaria",
        "lat": "42.696693420410156",
        "long": "23.411436080932614",
        "tags": {HOTEL, CULTURE, ARCHITECTURE, SEA},
        "temp": [
            2.2,
            4.9,
            9.8,
            15.7,
            20.3,
            23.5,
            25.9,
            26.0,
            22.6,
            16.6,
            9.6,
            4.1,
            15.1,
        ],
    },
    {
        "code": "PEK",
        "description": "Beijing is famous for its unusual diversity and contradictions. Contrasts can be seen in the city from the first sight - old temples from the imperial times are mixed with modern, glass skyscrapers. The size of the metropolis and the crowds in it are also dazzling. Beijing is more than 30 times bigger than Warsaw and it is inhabited by almost 20 million people. The biggest attraction is the Forbidden City - the seat of the Emperors of the Ming and Qing dynasties from the fifteenth century.",
        "pf": "1",
        "name": "Beijing",
        "country": "China",
        "lat": "40.0801010131836",
        "long": "116.58499908447266",
        "tags": {FOOD, CULTURE, ARCHITECTURE, CITY, HOTEL, EXPERIENCE, LANDSCAPE},
        "temp": [
            1.6,
            4.0,
            11.3,
            19.9,
            26.4,
            30.3,
            30.8,
            29.5,
            25.8,
            19.0,
            10.1,
            3.3,
            17.7,
        ],
    },
    {
        "code": "KUL",
        "description": "A visit to the capital of Malaysia is a feast for all the senses. The city landscape is decorated with skyscrapers, minarets and lush parks. The walks are accompanied by amazing aromas of freshly prepared dishes and drinks. Kuala Lumpur is characterized by multiculturalism which is perfectly reflected in the colorful Chinatown and fragrant Little India. This is one of our many connections to Asia, Australia and New Zealand, prepared with partner airlines with a convenient transfer in Singapore.",
        "pf": "1,1",
        "name": "Kuala Lumpur",
        "country": "Malaysia",
        "lat": "2.7455799579619997",
        "long": "101.70999908446998",
        "tags": {FOOD, HOTEL, CULTURE, SEA, LANDSCAPE, HOT, ARCHITECTURE, SPORT},
        "temp": [
            32.1,
            32.9,
            33.2,
            33.1,
            32.9,
            32.7,
            32.3,
            32.3,
            32.1,
            32.1,
            31.6,
            31.5,
            32.4,
        ],
    },
    {
        "code": "LWO",
        "description": "A walk along the streets of Lviv is a treat for enthusiasts of modernism. Next to numerous monuments there are many pearls of modernist architecture. Lviv is also famous for its majestic memorials. One of the most popular is Adam Mickiewicz’s statue.",
        "pf": "0,8",
        "name": "Lvov",
        "country": "Ukraine",
        "lat": "49.8125",
        "long": "23.95610046386719",
        "tags": {FOOD, ARCHITECTURE, CITY, CULTURE, HOTEL},
        "temp": [
            -2.6,
            -1.1,
            4.3,
            13.6,
            20.5,
            23.5,
            24.5,
            24.0,
            19.1,
            12.3,
            4.8,
            0.1,
            11.9,
        ],
    },
    {
        "code": "DEL",
        "description": "A journey through Delhi is like using a time machine. On the one hand, it is a modern city full of spectacular office buildings, sumptuous shopping centers, and centers that excel in futuristic information and telecommunications technologies. On the other hand, Delhi has three monuments, which were inscribed on the UNESCO List. Visit in Delhi is a great opportunity to taste local delicacies: curry, samosa or naan.",
        "pf": "0,9",
        "name": "Delhi",
        "country": "India",
        "lat": "28.5665",
        "long": "77.103104",
        "tags": {EXPERIENCE, HOT, HOTEL, FOOD, LANDSCAPE, HOT},
        "temp": [
            20.8,
            23.7,
            29.6,
            36.0,
            39.8,
            39.4,
            35.2,
            33.6,
            34.0,
            32.9,
            28.0,
            22.7,
            31.3,
        ],
    },
    {
        "code": "LAX",
        "description": "Los Angeles is a city connected with nature, where bustling neighborhoods combine with golden beaches and hills densely woven by plants. It is also a global center of creativity and entertainment. It attracts courageous dreamers and creators to realize their visions on stages and film studios.",
        "pf": "1,5",
        "name": "Los Angeles",
        "country": "United States",
        "lat": "33.94250107",
        "long": "-118.40799709999999",
        "tags": {EXPERIENCE, HOT, SEA, CITY, HOTEL, SPORT},
        "temp": [
            20.1,
            20.3,
            21.2,
            22.6,
            23.6,
            25.6,
            28.4,
            29.1,
            28.4,
            25.8,
            22.7,
            19.8,
            24.0,
        ],
    },
]
