from api.tags import *

IMAGE_MAP = {
    "city1.jpg": {"tags": {CITY, HOTEL, ARCHITECTURE}, "pf": 1.5},
    "city2.jpg": {"tags": {CITY, NIGHT_LIFE}, "pf": 2.0},
    "city3.jpg": {"tags": {CITY, HOTEL, ARCHITECTURE}, "pf": 1.2},
    "city4.jpg": {"tags": {CITY, HOTEL, EXPERIENCE, CULTURE}, "pf": 0.9},
    "city5.jpg": {"tags": {CULTURE, CITY, ARCHITECTURE}, "pf": 2.0},
    "city6.jpg": {"tags": {ARCHITECTURE, CITY, HOTEL}, "pf": 2.0},
    "city7.jpg": {"tags": {ARCHITECTURE, CITY, HOTEL}, "pf": 2.0},
    "city8.jpg": {"tags": {ARCHITECTURE, CITY, CULTURE}, "pf": 2.0},
    "desert1.jpg": {"tags": {WILDERNESS, EXPERIENCE, HOT}, "pf": 0.9},
    "desert2.jpg": {"tags": {WILDERNESS, EXPERIENCE, LANDSCAPE, HOT}, "pf": 1.1},
    "food1.jpg": {"tags": {FOOD, HOTEL}, "pf": 1.6},
    "food2.jpg": {"tags": {FOOD, EXPERIENCE, HOTEL}, "pf": 0.8},
    "food3.jpg": {"tags": {FOOD, EXPERIENCE, CULTURE}, "pf": 1},
    "food4.jpg": {"tags": {FOOD, CULTURE}, "pf": 1},
    "sea1.jpg": {"tags": {SEA, HOT}, "pf": 1.1},
    "sea2.jpg": {"tags": {SEA, HOT}, "pf": 0.9},
    "sea3.jpg": {"tags": {SEA, TENT}, "pf": 0.9},
    "sea4.jpg": {"tags": {SEA, HOT, HOTEL}, "pf": 2.0},
    "exp1.jpg": {"tags": {EXPERIENCE, LANDSCAPE, CULTURE}, "pf": 1.6},
    "exp2.jpg": {"tags": {SPORT, EXPERIENCE, TENT}, "pf": 0.5},
    "exp3.jpg": {"tags": {EXPERIENCE, HOTEL, LANDSCAPE}, "pf": 1.5},
    "exp4.jpg": {"tags": {EXPERIENCE, HOTEL, ARCHITECTURE, CITY}, "pf": 1.5},
    "exp5.jpg": {"tags": {EXPERIENCE, LANDSCAPE}, "pf": 1.0},
    "exp6.jpg": {"tags": {EXPERIENCE, LANDSCAPE, MOUNTAIN, TENT}, "pf": 1.0},
    "lake1.jpg": {"tags": {EXPERIENCE, LANDSCAPE, TENT, LAKE, SPORT}, "pf": 0.8},
    "lake2.jpg": {"tags": {LANDSCAPE, LAKE}, "pf": 1.1},
    "lake3.jpg": {"tags": {LANDSCAPE, LAKE, EXPERIENCE}, "pf": 1.1},
    "lake4.jpg": {"tags": {LANDSCAPE, LAKE, MOUNTAIN}, "pf": 1.1},
    "mountain1.jpg": {"tags": {MOUNTAIN, LAKE, LANDSCAPE}, "pf": 0.8},
    "mountain2.jpg": {"tags": {MOUNTAIN, LANDSCAPE, COLD}, "pf": 0.8},
    "mountain3.jpg": {"tags": {MOUNTAIN, LANDSCAPE, COLD, TENT}, "pf": 1.3},
    "mountain4.jpg": {"tags": {MOUNTAIN, LANDSCAPE, COLD, SKI, SPORT}, "pf": 1.6},
    "mountain5.jpg": {"tags": {MOUNTAIN, TENT, LANDSCAPE}, "pf": 0.8},
    "mountain6.jpg": {"tags": {MOUNTAIN, COLD, SKI}, "pf": 1.1},
    "mountain7.jpg": {"tags": {MOUNTAIN, HOTEL, LAKE, LANDSCAPE}, "pf": 1.3},
    "tent2.jpg": {"tags": {EXPERIENCE, WILDERNESS, TENT, LANDSCAPE}, "pf": 0.4},
}
