from api.tags import *

IMAGE_MAP = {
    "building1.jpg": {"tags": {ARCHITECTURE}, "pf": 1.5},
    "city1.jpg": {"tags": {CITY, HOTEL}, "pf": 1.5},
    "city2.jpg": {"tags": {EXPERIENCE, NIGHT_LIFE}, "pf": 2.0},
    "city3.jpg": {"tags": {CITY, ARCHITECTURE}, "pf": 1.2},
    "city4.jpg": {"tags": {EXPERIENCE, CULTURE}, "pf": 0.9},
    "city5.jpg": {"tags": {CULTURE, ARCHITECTURE}, "pf": 2.0},
    "city6.jpg": {"tags": {CITY}, "pf": 2.0},
    "city7.jpg": {"tags": {UNIQUE, CULTURE}, "pf": 2.0},
    "city8.jpg": {"tags": {UNIQUE, ARCHITECTURE, CULTURE}, "pf": 2.0},
    "culture1.jpg": {"tags": {UNIQUE, CULTURE}, "pf": 0.9},
    "desert1.jpg": {"tags": {UNIQUE, WILDERNESS, EXPERIENCE, HOT}, "pf": 0.9},
    "desert2.jpg": {"tags": {WILDERNESS, LANDSCAPE, HOT}, "pf": 1.1},
    "exp1.jpg": {"tags": {EXPERIENCE, LANDSCAPE}, "pf": 1.6},
    "exp2.jpg": {"tags": {SPORT, TENT}, "pf": 0.5},
    "exp3.jpg": {"tags": {UNIQUE, LANDSCAPE}, "pf": 1.5},
    "exp4.jpg": {"tags": {CITY, ARCHITECTURE}, "pf": 1.5},
    "exp5.jpg": {"tags": {UNIQUE, WILDERNESS, TENT}, "pf": 1.0},
    "exp6.jpg": {"tags": {LANDSCAPE, MOUNTAIN, TENT}, "pf": 1.0},
    "food1.jpg": {"tags": {FOOD, HOTEL}, "pf": 1.6},
    "food2.jpg": {"tags": {FOOD, EXPERIENCE, HOTEL}, "pf": 0.8},
    "food3.jpg": {"tags": {UNIQUE, FOOD}, "pf": 1},
    "food4.jpg": {"tags": {FOOD, CULTURE}, "pf": 1},
    "hot1.jpg": {"tags": {HOT, LANDSCAPE}, "pf": 1},
    "hotel1.jpg": {"tags": {HOTEL, HOT}, "pf": 1},
    "hotel2.jpg": {"tags": {HOTEL, UNIQUE}, "pf": 1},
    "lake1.jpg": {"tags": {EXPERIENCE, TENT, LAKE, SPORT}, "pf": 0.8},
    "lake2.jpg": {"tags": {LANDSCAPE, LAKE}, "pf": 1.1},
    "lake3.jpg": {"tags": {LAKE, EXPERIENCE}, "pf": 1.1},
    "lake4.jpg": {"tags": {COLD, LAKE, MOUNTAIN}, "pf": 1.1},
    "lake5.jpg": {"tags": {LAKE, TENT}, "pf": 1.1},
    "mountain1.jpg": {"tags": {MOUNTAIN, LAKE}, "pf": 0.8},
    "mountain2.jpg": {"tags": {LANDSCAPE, SKI, COLD}, "pf": 0.8},
    "mountain3.jpg": {"tags": {WILDERNESS, COLD, TENT}, "pf": 1.3},
    "mountain4.jpg": {"tags": {MOUNTAIN, COLD, SKI, SPORT}, "pf": 1.6},
    "mountain5.jpg": {"tags": {MOUNTAIN, TENT, LANDSCAPE}, "pf": 0.8},
    "mountain6.jpg": {"tags": {MOUNTAIN, COLD}, "pf": 1.1},
    "mountain7.jpg": {"tags": {MOUNTAIN, HOTEL, LAKE}, "pf": 1.3},
    "night1.jpg": {"tags": {NIGHT_LIFE}, "pf": 1.3},
    "night2.jpg": {"tags": {NIGHT_LIFE, CITY, UNIQUE}, "pf": 1.3},
    "night3.jpg": {"tags": {NIGHT_LIFE, CITY}, "pf": 1.3},
    "sea1.jpg": {"tags": {SEA, HOT}, "pf": 1.1},
    "sea2.jpg": {"tags": {SEA, HOT}, "pf": 0.9},
    "sea3.jpg": {"tags": {SEA, TENT}, "pf": 0.9},
    "sea4.jpg": {"tags": {UNIQUE, SEA, HOT, HOTEL}, "pf": 2.0},
    "sport1.jpg": {"tags": {SPORT}, "pf": 2.0},
    "sport2.jpg": {"tags": {SPORT, SKI, COLD}, "pf": 2.0},
    "sport3.jpg": {"tags": {SPORT, SKI, EXPERIENCE}, "pf": 2.0},
    "sport4.jpg": {"tags": {SPORT, SEA}, "pf": 2.0},
    "sport5.jpg": {"tags": {SPORT, HOT, CITY}, "pf": 2.0},
    "tent1.jpg": {"tags": {TENT, WILDERNESS}, "pf": 0.4},
    "tent2.jpg": {"tags": {TENT, COLD}, "pf": 0.4},
}
