# tags
FOOD = "food"
CULTURE = "culture"
LANDSCAPE = "landscape"
ARCHITECTURE = "architecture"
MOUNTAIN = "mountain"
SEA = "sea"
LAKE = "lake"
CITY = "city"
NIGHT_LIFE = "night_life"
WILDERNESS = "wilderness"
EXPERIENCE = "experience"
HOT = "hot"
COLD = "cold"
HOTEL = "hotel"
TENT = "tent"